# This is a basic workflow to help you get started with Actions

name: "get-latest-results"

# Controls when the workflow will run
on:
  schedule:
    - cron:  '30 18 * * 0'    # At every Sunday 18:30

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  get-stats:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Get current year
        id: date
        run: if [ $(date +%m) -le 6 ]; then echo "::set-output name=current_year::$(date -d 'last year' +%Y)"; else echo "::set-output name=current_year::$(date +%Y)"; fi
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Get API data and save files
        id: rapid-api-call
        run: |
          current_round_string=$(curl -H "x-rapidapi-key: ${{ secrets.API_SPORTS_IO_KEY }}" -H "x-rapidapi-host: v3.football.api-sports.io" "https://v3.football.api-sports.io/fixtures/rounds?league=207&season=${{ steps.date.outputs.current_year }}&current=true" | jq -r '.response[0]')
          current_round_number=$(echo ${current_round_string} | grep -P '\d+(?!.*-)' -o)
          current_round_string_query_parameter=$(echo ${current_round_string} | sed -r 's/[ ]+/%20/g')
          echo "::set-output name=current_round_number::$(echo ${current_round_number})"
          curl -H "x-rapidapi-key: ${{ secrets.API_SPORTS_IO_KEY }}" -H "x-rapidapi-host: v3.football.api-sports.io" -o latest_standings.json "https://v3.football.api-sports.io/standings?league=207&season=${{ steps.date.outputs.current_year }}"
          cp latest_standings.json ${{ steps.date.outputs.current_year }}_${current_round_number}_standings.json
          curl -H "x-rapidapi-key: ${{ secrets.API_SPORTS_IO_KEY }}" -H "x-rapidapi-host: v3.football.api-sports.io" -o latest_round.json "https://v3.football.api-sports.io/fixtures?league=207&season=${{ steps.date.outputs.current_year }}&round=${current_round_string_query_parameter}"
          cp latest_round.json ${{ steps.date.outputs.current_year }}_${current_round_number}_round.json

      - name: Pushes latest round to data store
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.BENSO_BOT }}
        with:
          git_server: 'github.com'
          source_file: 'latest_standings.json'
          destination_repo: 'BensoGmbH/superleague-data-store'
          destination_branch: 'master'
          user_email: ${{ secrets.BENSO_EMAIL }}
          user_name: 'benso-bot'
          commit_message: 'added latest standings'

      - name: Pushes latest round to data store
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.BENSO_BOT }}
        with:
          git_server: 'github.com'
          source_file: 'latest_round.json'
          destination_repo: 'BensoGmbH/superleague-data-store'
          destination_branch: 'master'
          user_email: ${{ secrets.BENSO_EMAIL }}'
          user_name: 'benso-bot'
          commit_message: 'added latest round'

      - name: Pushes standings to data-store archive
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.BENSO_BOT }}
        with:
          git_server: 'github.com'
          source_file: '${{ steps.date.outputs.current_year }}_${{ steps.rapid-api-call.outputs.current_round_number }}_standings.json'
          destination_repo: 'BensoGmbH/superleague-data-store'
          destination_branch: 'master'
          user_email: ${{ secrets.BENSO_EMAIL }}
          user_name: 'benso-bot'
          commit_message: 'added standing ${{ steps.date.outputs.current_year }}_${{ steps.rapid-api-call.outputs.current_round_number }}'

      - name: Pushes round to data-store archive
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.BENSO_BOT }}
        with:
          git_server: 'github.com'
          source_file: '${{ steps.date.outputs.current_year }}_${{ steps.rapid-api-call.outputs.current_round_number }}_round.json'
          destination_repo: 'BensoGmbH/superleague-data-store'
          destination_branch: 'master'
          user_email: ${{ secrets.BENSO_EMAIL }}
          user_name: 'benso-bot'
          commit_message: 'added round ${{ steps.date.outputs.current_year }}_${{ steps.rapid-api-call.outputs.current_round_number }}'
      
