# This is a basic workflow to help you get started with Actions

name: "get-latest-results"

# Controls when the workflow will run
on:
  schedule:
    - cron:  '30 18 * * 0'    # At every Sunday 18:30

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "get-stats"
  get-stats:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Runs a set of commands using the runners shell
      - name: Get API data and save to files
        run: |
          current_week=`date +"%U"`
          curl -H "x-rapidapi-key: ${{ secrets.RAPID_API_KEY }}" -H "x-rapidapi-host: v3.football.api-sports.io" -o latest_standings.json "https://v3.football.api-sports.io/standings?league=207&season=2021"
          cp latest_standings.json standings_${current_week}.json
          current_round=$(curl -H "x-rapidapi-key: ${{ secrets.RAPID_API_KEY }}" -H "x-rapidapi-host: v3.football.api-sports.io" "https://v3.football.api-sports.io/fixtures/rounds?league=207&season=2021&current=true" | jq -r '.response[0]' | sed -r 's/[ ]+/%20/g')
          curl -H "x-rapidapi-key: ${{ secrets.RAPID_API_KEY }}" -H "x-rapidapi-host: v3.football.api-sports.io" -o latest_round.json "https://v3.football.api-sports.io/fixtures?league=207?season=2021?round=${current_round}"
          cp latest_round.json round_${current_week}.json
          
      

